// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Entities
 */
export type Entities = {
    /**
     * Events
     *
     * A list of events related to the entity.
     */
    events?: Array<Event>;
    /**
     * Sources
     *
     * A list of sources related to the entity.
     */
    sources?: Array<Source>;
    /**
     * People
     *
     * A list of persons related to the entity.
     */
    people?: Array<Person>;
    /**
     * Organizations
     *
     * A list of organizations related to the entity.
     */
    organizations?: Array<Organization>;
    /**
     * Websites
     *
     * A list of websites related to the entity.
     */
    websites?: Array<Website>;
    /**
     * Relations
     *
     * A list of relations related to the entity.
     */
    relations?: Array<Relation>;
};

/**
 * EntityConnectionRequest
 */
export type EntityConnectionRequest = {
    /**
     * Entity Id
     *
     * The ID of the entity to connect to the view.
     */
    entity_id: string;
};

/**
 * Event
 *
 * Represents an event.
 */
export type Event = {
    /**
     * Type
     *
     * Type of event
     */
    type?: string | null;
    /**
     * Location of the event
     */
    location?: LocationData | null;
    /**
     * Title
     *
     * Title of the event. Keep it short and clear.
     */
    title?: string | null;
    /**
     * Description
     *
     * Brief description of the event. Keep it short and clear.
     */
    description?: string | null;
    /**
     * Happened At
     *
     * Timestamp when the event happened
     */
    happened_at?: number | null;
    /**
     * Tags
     *
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
    /**
     * Owner
     *
     * Owner of the document
     */
    owner?: string;
    /**
     * Read
     *
     * Users/Roles with read access
     */
    read?: Array<string>;
    /**
     * Write
     *
     * Users/Roles with write access
     */
    write?: Array<string>;
    /**
     * Id
     *
     * ArangoDB document ID
     */
    _id?: string | null;
    /**
     * Key
     *
     * ArangoDB document key
     */
    _key?: string | null;
    /**
     * Rev
     *
     * ArangoDB document revision
     */
    _rev?: string | null;
    /**
     * Created At
     *
     * Data creation timestamp
     */
    created_at?: number | null;
    /**
     * Updated At
     *
     * Data update timestamp
     */
    updated_at?: number | null;
};

/**
 * EventMainData
 */
export type EventMainData = {
    /**
     * Type
     *
     * Type of event
     */
    type?: string | null;
    /**
     * Location of the event
     */
    location?: LocationData | null;
    /**
     * Title
     *
     * Title of the event. Keep it short and clear.
     */
    title?: string | null;
    /**
     * Description
     *
     * Brief description of the event. Keep it short and clear.
     */
    description?: string | null;
    /**
     * Happened At
     *
     * Timestamp when the event happened
     */
    happened_at?: number | null;
    /**
     * Tags
     *
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LocationData
 *
 * Represents geographical location data.
 */
export type LocationData = {
    /**
     * Latitude
     *
     * Latitude
     */
    latitude: number;
    /**
     * Longitude
     *
     * Longitude
     */
    longitude: number;
    /**
     * Country Code
     *
     * ISO country code
     */
    country_code: string;
    /**
     * Administrative Area
     *
     * Administrative area (e.g., state, province)
     */
    administrative_area: string;
    /**
     * Sub Administrative Area
     *
     * Sub-administrative area
     */
    sub_administrative_area?: string;
    /**
     * Locality
     *
     * Locality (e.g., city, town)
     */
    locality: string;
    /**
     * Sub Locality
     *
     * Sub-locality
     */
    sub_locality?: string;
    /**
     * Address
     *
     * Full address
     */
    address: string;
    /**
     * Postal Code
     *
     * Postal code
     */
    postal_code: number;
};

/**
 * Organization
 *
 * Represents an organization.
 */
export type Organization = {
    /**
     * Type
     *
     * Type of organization
     */
    type?: string | null;
    /**
     * Name
     *
     * Name of the organization
     */
    name?: string | null;
    /**
     * Founded At
     *
     * When organization is founded (timestamp)
     */
    founded_at?: number | null;
    /**
     * Discovered At
     *
     * When organization is discovered (timestamp)
     */
    discovered_at?: number | null;
    /**
     * Last Visited
     *
     * When organization is last visited (timestamp)
     */
    last_visited?: number | null;
    /**
     * Tags
     *
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
    /**
     * Owner
     *
     * Owner of the document
     */
    owner?: string;
    /**
     * Read
     *
     * Users/Roles with read access
     */
    read?: Array<string>;
    /**
     * Write
     *
     * Users/Roles with write access
     */
    write?: Array<string>;
    /**
     * Id
     *
     * ArangoDB document ID
     */
    _id?: string | null;
    /**
     * Key
     *
     * ArangoDB document key
     */
    _key?: string | null;
    /**
     * Rev
     *
     * ArangoDB document revision
     */
    _rev?: string | null;
    /**
     * Created At
     *
     * Data creation timestamp
     */
    created_at?: number | null;
    /**
     * Updated At
     *
     * Data update timestamp
     */
    updated_at?: number | null;
};

/**
 * OrganizationMainData
 */
export type OrganizationMainData = {
    /**
     * Type
     *
     * Type of organization
     */
    type?: string | null;
    /**
     * Name
     *
     * Name of the organization
     */
    name?: string | null;
    /**
     * Founded At
     *
     * When organization is founded (timestamp)
     */
    founded_at?: number | null;
    /**
     * Discovered At
     *
     * When organization is discovered (timestamp)
     */
    discovered_at?: number | null;
    /**
     * Last Visited
     *
     * When organization is last visited (timestamp)
     */
    last_visited?: number | null;
    /**
     * Tags
     *
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
};

/**
 * OsintView
 */
export type OsintView = {
    /**
     * Owner
     *
     * Owner of the document
     */
    owner?: string;
    /**
     * Read
     *
     * Users/Roles with read access
     */
    read?: Array<string>;
    /**
     * Write
     *
     * Users/Roles with write access
     */
    write?: Array<string>;
    /**
     * Id
     *
     * ArangoDB document ID
     */
    _id?: string | null;
    /**
     * Key
     *
     * ArangoDB document key
     */
    _key?: string | null;
    /**
     * Rev
     *
     * ArangoDB document revision
     */
    _rev?: string | null;
    /**
     * Created At
     *
     * Data creation timestamp
     */
    created_at?: number | null;
    /**
     * Updated At
     *
     * Data update timestamp
     */
    updated_at?: number | null;
    /**
     * Name
     *
     * Name of the view
     */
    name?: string | null;
    /**
     * Description
     *
     * Description of the view
     */
    description?: string | null;
    /**
     * Analysis
     *
     * Json based analysis report doc
     */
    analysis?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * OsintViewMainData
 */
export type OsintViewMainData = {
    /**
     * Name
     *
     * Name of the view
     */
    name?: string | null;
    /**
     * Description
     *
     * Description of the view
     */
    description?: string | null;
    /**
     * Analysis
     *
     * Json based analysis report doc
     */
    analysis?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * Permissive
 *
 * Base class for permission-related fields.
 */
export type Permissive = {
    /**
     * Owner
     *
     * Owner of the document
     */
    owner?: string;
    /**
     * Read
     *
     * Users/Roles with read access
     */
    read?: Array<string>;
    /**
     * Write
     *
     * Users/Roles with write access
     */
    write?: Array<string>;
};

/**
 * Person
 *
 * Represents a person.
 */
export type Person = {
    /**
     * Type
     *
     * Role type of person
     */
    type?: string | null;
    /**
     * Role
     *
     * Role
     */
    role?: string | null;
    /**
     * Name
     *
     * Name
     */
    name?: string | null;
    /**
     * Nationality
     *
     * Nationality
     */
    nationality?: string | null;
    /**
     * Birth Date
     *
     * Person's birth date (timestamp)
     */
    birth_date?: number | null;
    /**
     * Tags
     *
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Aliases
     *
     * Aliases
     */
    aliases?: Array<string> | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
    /**
     * Owner
     *
     * Owner of the document
     */
    owner?: string;
    /**
     * Read
     *
     * Users/Roles with read access
     */
    read?: Array<string>;
    /**
     * Write
     *
     * Users/Roles with write access
     */
    write?: Array<string>;
    /**
     * Id
     *
     * ArangoDB document ID
     */
    _id?: string | null;
    /**
     * Key
     *
     * ArangoDB document key
     */
    _key?: string | null;
    /**
     * Rev
     *
     * ArangoDB document revision
     */
    _rev?: string | null;
    /**
     * Created At
     *
     * Data creation timestamp
     */
    created_at?: number | null;
    /**
     * Updated At
     *
     * Data update timestamp
     */
    updated_at?: number | null;
};

/**
 * PersonMainData
 */
export type PersonMainData = {
    /**
     * Type
     *
     * Role type of person
     */
    type?: string | null;
    /**
     * Role
     *
     * Role
     */
    role?: string | null;
    /**
     * Name
     *
     * Name
     */
    name?: string | null;
    /**
     * Nationality
     *
     * Nationality
     */
    nationality?: string | null;
    /**
     * Birth Date
     *
     * Person's birth date (timestamp)
     */
    birth_date?: number | null;
    /**
     * Tags
     *
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Aliases
     *
     * Aliases
     */
    aliases?: Array<string> | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
};

/**
 * QueryViewsResponse
 */
export type QueryViewsResponse = {
    /**
     * Views
     *
     * A list of views
     */
    views?: Array<OsintView>;
    /**
     * Offset
     *
     * The offset from which to start returning results.
     */
    offset?: number;
};

/**
 * Relation
 *
 * Represents a relationship between two entities.
 */
export type Relation = {
    /**
     * Name
     *
     * Name of the relation used in database key (must be ascii letters)
     */
    name?: string | null;
    /**
     * Confidence
     *
     * Confidence score
     */
    confidence?: number | null;
    /**
     * Label
     *
     * Label name of the relation (can be any language) to display
     */
    label?: string | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
    /**
     * From
     *
     * Source document ID
     */
    _from?: string | null;
    /**
     * To
     *
     * Target document ID
     */
    _to?: string | null;
    /**
     * Owner
     *
     * Owner of the document
     */
    owner?: string;
    /**
     * Read
     *
     * Users/Roles with read access
     */
    read?: Array<string>;
    /**
     * Write
     *
     * Users/Roles with write access
     */
    write?: Array<string>;
    /**
     * Id
     *
     * ArangoDB document ID
     */
    _id?: string | null;
    /**
     * Key
     *
     * ArangoDB document key
     */
    _key?: string | null;
    /**
     * Rev
     *
     * ArangoDB document revision
     */
    _rev?: string | null;
    /**
     * Created At
     *
     * Data creation timestamp
     */
    created_at?: number | null;
    /**
     * Updated At
     *
     * Data update timestamp
     */
    updated_at?: number | null;
};

/**
 * RelationMainData
 */
export type RelationMainData = {
    /**
     * Name
     *
     * Name of the relation used in database key (must be ascii letters)
     */
    name?: string | null;
    /**
     * Confidence
     *
     * Confidence score
     */
    confidence?: number | null;
    /**
     * Label
     *
     * Label name of the relation (can be any language) to display
     */
    label?: string | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
    /**
     * From
     *
     * Source document ID
     */
    _from?: string | null;
    /**
     * To
     *
     * Target document ID
     */
    _to?: string | null;
};

/**
 * Source
 *
 * Represents a source of information.
 */
export type Source = {
    /**
     * Type
     *
     * Type of source
     */
    type?: string | null;
    /**
     * Url
     *
     * URL
     */
    url?: string | null;
    /**
     * Name
     *
     * Name of the source
     */
    name?: string | null;
    /**
     * Title
     *
     * Title of the source. Keep it short and clear.
     */
    title?: string | null;
    /**
     * Description
     *
     * Brief description of the source. Keep it short and clear.
     */
    description?: string | null;
    /**
     * Reliability
     *
     * Reliability score
     */
    reliability?: number | null;
    /**
     * Tags
     *
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
    /**
     * Owner
     *
     * Owner of the document
     */
    owner?: string;
    /**
     * Read
     *
     * Users/Roles with read access
     */
    read?: Array<string>;
    /**
     * Write
     *
     * Users/Roles with write access
     */
    write?: Array<string>;
    /**
     * Id
     *
     * ArangoDB document ID
     */
    _id?: string | null;
    /**
     * Key
     *
     * ArangoDB document key
     */
    _key?: string | null;
    /**
     * Rev
     *
     * ArangoDB document revision
     */
    _rev?: string | null;
    /**
     * Created At
     *
     * Data creation timestamp
     */
    created_at?: number | null;
    /**
     * Updated At
     *
     * Data update timestamp
     */
    updated_at?: number | null;
};

/**
 * SourceMainData
 */
export type SourceMainData = {
    /**
     * Type
     *
     * Type of source
     */
    type?: string | null;
    /**
     * Url
     *
     * URL
     */
    url?: string | null;
    /**
     * Name
     *
     * Name of the source
     */
    name?: string | null;
    /**
     * Title
     *
     * Title of the source. Keep it short and clear.
     */
    title?: string | null;
    /**
     * Description
     *
     * Brief description of the source. Keep it short and clear.
     */
    description?: string | null;
    /**
     * Reliability
     *
     * Reliability score
     */
    reliability?: number | null;
    /**
     * Tags
     *
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Website
 *
 * Represents a website.
 */
export type Website = {
    /**
     * Type
     *
     * Type of website
     */
    type?: string | null;
    /**
     * Url
     *
     * URL
     */
    url?: string | null;
    /**
     * Title
     *
     * Title of the website. Keep it short and clear.
     */
    title?: string | null;
    /**
     * Description
     *
     * Brief description of the website. Keep it short and clear.
     */
    description?: string | null;
    /**
     * Founded At
     *
     * When website is founded (timestamp)
     */
    founded_at?: number | null;
    /**
     * Discovered At
     *
     * When website is discovered (timestamp)
     */
    discovered_at?: number | null;
    /**
     * Last Visited
     *
     * When website is last visited (timestamp)
     */
    last_visited?: number | null;
    /**
     * Tags
     *
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
    /**
     * Owner
     *
     * Owner of the document
     */
    owner?: string;
    /**
     * Read
     *
     * Users/Roles with read access
     */
    read?: Array<string>;
    /**
     * Write
     *
     * Users/Roles with write access
     */
    write?: Array<string>;
    /**
     * Id
     *
     * ArangoDB document ID
     */
    _id?: string | null;
    /**
     * Key
     *
     * ArangoDB document key
     */
    _key?: string | null;
    /**
     * Rev
     *
     * ArangoDB document revision
     */
    _rev?: string | null;
    /**
     * Created At
     *
     * Data creation timestamp
     */
    created_at?: number | null;
    /**
     * Updated At
     *
     * Data update timestamp
     */
    updated_at?: number | null;
};

/**
 * WebsiteMainData
 */
export type WebsiteMainData = {
    /**
     * Type
     *
     * Type of website
     */
    type?: string | null;
    /**
     * Url
     *
     * URL
     */
    url?: string | null;
    /**
     * Title
     *
     * Title of the website. Keep it short and clear.
     */
    title?: string | null;
    /**
     * Description
     *
     * Brief description of the website. Keep it short and clear.
     */
    description?: string | null;
    /**
     * Founded At
     *
     * When website is founded (timestamp)
     */
    founded_at?: number | null;
    /**
     * Discovered At
     *
     * When website is discovered (timestamp)
     */
    discovered_at?: number | null;
    /**
     * Last Visited
     *
     * When website is last visited (timestamp)
     */
    last_visited?: number | null;
    /**
     * Tags
     *
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
};

export type GetPersonData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/persons';
};

export type GetPersonErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPersonError = GetPersonErrors[keyof GetPersonErrors];

export type GetPersonResponses = {
    /**
     * Successful Response
     */
    200: Person;
};

export type GetPersonResponse = GetPersonResponses[keyof GetPersonResponses];

export type CreatePersonData = {
    body: PersonMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/persons';
};

export type CreatePersonErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePersonError = CreatePersonErrors[keyof CreatePersonErrors];

export type CreatePersonResponses = {
    /**
     * Successful Response
     */
    200: Person;
};

export type CreatePersonResponse = CreatePersonResponses[keyof CreatePersonResponses];

export type UpdatePersonData = {
    body: PersonMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/persons';
};

export type UpdatePersonErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePersonError = UpdatePersonErrors[keyof UpdatePersonErrors];

export type UpdatePersonResponses = {
    /**
     * Successful Response
     */
    200: Person;
};

export type UpdatePersonResponse = UpdatePersonResponses[keyof UpdatePersonResponses];

export type GetOrganizationData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/organizations';
};

export type GetOrganizationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrganizationError = GetOrganizationErrors[keyof GetOrganizationErrors];

export type GetOrganizationResponses = {
    /**
     * Successful Response
     */
    200: Organization;
};

export type GetOrganizationResponse = GetOrganizationResponses[keyof GetOrganizationResponses];

export type CreateOrganizationData = {
    body: OrganizationMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/organizations';
};

export type CreateOrganizationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOrganizationError = CreateOrganizationErrors[keyof CreateOrganizationErrors];

export type CreateOrganizationResponses = {
    /**
     * Successful Response
     */
    200: Organization;
};

export type CreateOrganizationResponse = CreateOrganizationResponses[keyof CreateOrganizationResponses];

export type UpdateOrganizationData = {
    body: OrganizationMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/organizations';
};

export type UpdateOrganizationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOrganizationError = UpdateOrganizationErrors[keyof UpdateOrganizationErrors];

export type UpdateOrganizationResponses = {
    /**
     * Successful Response
     */
    200: Organization;
};

export type UpdateOrganizationResponse = UpdateOrganizationResponses[keyof UpdateOrganizationResponses];

export type GetEventData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/events';
};

export type GetEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventError = GetEventErrors[keyof GetEventErrors];

export type GetEventResponses = {
    /**
     * Successful Response
     */
    200: Event;
};

export type GetEventResponse = GetEventResponses[keyof GetEventResponses];

export type CreateEventData = {
    body: EventMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/events';
};

export type CreateEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEventError = CreateEventErrors[keyof CreateEventErrors];

export type CreateEventResponses = {
    /**
     * Successful Response
     */
    200: Event;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type UpdateEventData = {
    body: EventMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/events';
};

export type UpdateEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEventError = UpdateEventErrors[keyof UpdateEventErrors];

export type UpdateEventResponses = {
    /**
     * Successful Response
     */
    200: Event;
};

export type UpdateEventResponse = UpdateEventResponses[keyof UpdateEventResponses];

export type GetWebsiteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/websites';
};

export type GetWebsiteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWebsiteError = GetWebsiteErrors[keyof GetWebsiteErrors];

export type GetWebsiteResponses = {
    /**
     * Successful Response
     */
    200: Website;
};

export type GetWebsiteResponse = GetWebsiteResponses[keyof GetWebsiteResponses];

export type CreateWebsiteData = {
    body: WebsiteMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/websites';
};

export type CreateWebsiteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWebsiteError = CreateWebsiteErrors[keyof CreateWebsiteErrors];

export type CreateWebsiteResponses = {
    /**
     * Successful Response
     */
    200: Website;
};

export type CreateWebsiteResponse = CreateWebsiteResponses[keyof CreateWebsiteResponses];

export type UpdateWebsiteData = {
    body: WebsiteMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/websites';
};

export type UpdateWebsiteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateWebsiteError = UpdateWebsiteErrors[keyof UpdateWebsiteErrors];

export type UpdateWebsiteResponses = {
    /**
     * Successful Response
     */
    200: Website;
};

export type UpdateWebsiteResponse = UpdateWebsiteResponses[keyof UpdateWebsiteResponses];

export type GetSourceData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/sources';
};

export type GetSourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSourceError = GetSourceErrors[keyof GetSourceErrors];

export type GetSourceResponses = {
    /**
     * Successful Response
     */
    200: Source;
};

export type GetSourceResponse = GetSourceResponses[keyof GetSourceResponses];

export type CreateSourceData = {
    body: SourceMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/sources';
};

export type CreateSourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSourceError = CreateSourceErrors[keyof CreateSourceErrors];

export type CreateSourceResponses = {
    /**
     * Successful Response
     */
    200: Source;
};

export type CreateSourceResponse = CreateSourceResponses[keyof CreateSourceResponses];

export type UpdateSourceData = {
    body: SourceMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/sources';
};

export type UpdateSourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSourceError = UpdateSourceErrors[keyof UpdateSourceErrors];

export type UpdateSourceResponses = {
    /**
     * Successful Response
     */
    200: Source;
};

export type UpdateSourceResponse = UpdateSourceResponses[keyof UpdateSourceResponses];

export type DeleteRelationData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    url: '/relations';
};

export type DeleteRelationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRelationError = DeleteRelationErrors[keyof DeleteRelationErrors];

export type DeleteRelationResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRelationData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/relations';
};

export type GetRelationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRelationError = GetRelationErrors[keyof GetRelationErrors];

export type GetRelationResponses = {
    /**
     * Successful Response
     */
    200: Relation;
};

export type GetRelationResponse = GetRelationResponses[keyof GetRelationResponses];

export type CreateRelationData = {
    body: RelationMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/relations';
};

export type CreateRelationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRelationError = CreateRelationErrors[keyof CreateRelationErrors];

export type CreateRelationResponses = {
    /**
     * Successful Response
     */
    200: Relation;
};

export type CreateRelationResponse = CreateRelationResponses[keyof CreateRelationResponses];

export type UpdateRelationData = {
    body: RelationMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
        /**
         * Include Pending
         */
        include_pending?: boolean;
    };
    url: '/relations';
};

export type UpdateRelationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRelationError = UpdateRelationErrors[keyof UpdateRelationErrors];

export type UpdateRelationResponses = {
    /**
     * Successful Response
     */
    200: Relation;
};

export type UpdateRelationResponse = UpdateRelationResponses[keyof UpdateRelationResponses];

export type DeleteViewData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    url: '/views';
};

export type DeleteViewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteViewError = DeleteViewErrors[keyof DeleteViewErrors];

export type DeleteViewResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetViewData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    url: '/views';
};

export type GetViewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetViewError = GetViewErrors[keyof GetViewErrors];

export type GetViewResponses = {
    /**
     * Successful Response
     */
    200: OsintView;
};

export type GetViewResponse = GetViewResponses[keyof GetViewResponses];

export type CreateViewData = {
    body: OsintViewMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/views';
};

export type CreateViewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateViewError = CreateViewErrors[keyof CreateViewErrors];

export type CreateViewResponses = {
    /**
     * Successful Response
     */
    200: OsintView;
};

export type CreateViewResponse = CreateViewResponses[keyof CreateViewResponses];

export type UpdateViewData = {
    body: OsintViewMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    url: '/views';
};

export type UpdateViewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateViewError = UpdateViewErrors[keyof UpdateViewErrors];

export type UpdateViewResponses = {
    /**
     * Successful Response
     */
    200: OsintView;
};

export type UpdateViewResponse = UpdateViewResponses[keyof UpdateViewResponses];

export type GetViewEntitiesData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    url: '/views/entities';
};

export type GetViewEntitiesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetViewEntitiesError = GetViewEntitiesErrors[keyof GetViewEntitiesErrors];

export type GetViewEntitiesResponses = {
    /**
     * Successful Response
     */
    200: Entities;
};

export type GetViewEntitiesResponse = GetViewEntitiesResponses[keyof GetViewEntitiesResponses];

export type ConnectEntityToViewData = {
    body: EntityConnectionRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    url: '/views/entities';
};

export type ConnectEntityToViewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConnectEntityToViewError = ConnectEntityToViewErrors[keyof ConnectEntityToViewErrors];

export type ConnectEntityToViewResponses = {
    /**
     * Successful Response
     */
    200: OsintView;
};

export type ConnectEntityToViewResponse = ConnectEntityToViewResponses[keyof ConnectEntityToViewResponses];

export type QueryViewsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Text
         */
        text?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/views/query';
};

export type QueryViewsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QueryViewsError = QueryViewsErrors[keyof QueryViewsErrors];

export type QueryViewsResponses = {
    /**
     * Successful Response
     */
    200: QueryViewsResponse;
};

export type QueryViewsResponse2 = QueryViewsResponses[keyof QueryViewsResponses];

export type UpdatePersonPermissionsData = {
    body: Permissive;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    url: '/persons/permissions';
};

export type UpdatePersonPermissionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePersonPermissionsError = UpdatePersonPermissionsErrors[keyof UpdatePersonPermissionsErrors];

export type UpdatePersonPermissionsResponses = {
    /**
     * Successful Response
     */
    200: Person;
};

export type UpdatePersonPermissionsResponse = UpdatePersonPermissionsResponses[keyof UpdatePersonPermissionsResponses];

export type UpdateOrganizationPermissionsData = {
    body: Permissive;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    url: '/organizations/permissions';
};

export type UpdateOrganizationPermissionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOrganizationPermissionsError = UpdateOrganizationPermissionsErrors[keyof UpdateOrganizationPermissionsErrors];

export type UpdateOrganizationPermissionsResponses = {
    /**
     * Successful Response
     */
    200: Organization;
};

export type UpdateOrganizationPermissionsResponse = UpdateOrganizationPermissionsResponses[keyof UpdateOrganizationPermissionsResponses];

export type UpdateEventPermissionsData = {
    body: Permissive;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    url: '/events/permissions';
};

export type UpdateEventPermissionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEventPermissionsError = UpdateEventPermissionsErrors[keyof UpdateEventPermissionsErrors];

export type UpdateEventPermissionsResponses = {
    /**
     * Successful Response
     */
    200: Event;
};

export type UpdateEventPermissionsResponse = UpdateEventPermissionsResponses[keyof UpdateEventPermissionsResponses];

export type UpdateWebsitePermissionsData = {
    body: Permissive;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    url: '/websites/permissions';
};

export type UpdateWebsitePermissionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateWebsitePermissionsError = UpdateWebsitePermissionsErrors[keyof UpdateWebsitePermissionsErrors];

export type UpdateWebsitePermissionsResponses = {
    /**
     * Successful Response
     */
    200: Website;
};

export type UpdateWebsitePermissionsResponse = UpdateWebsitePermissionsResponses[keyof UpdateWebsitePermissionsResponses];

export type UpdateSourcePermissionsData = {
    body: Permissive;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    url: '/sources/permissions';
};

export type UpdateSourcePermissionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSourcePermissionsError = UpdateSourcePermissionsErrors[keyof UpdateSourcePermissionsErrors];

export type UpdateSourcePermissionsResponses = {
    /**
     * Successful Response
     */
    200: Source;
};

export type UpdateSourcePermissionsResponse = UpdateSourcePermissionsResponses[keyof UpdateSourcePermissionsResponses];

export type UpdateRelationPermissionsData = {
    body: Permissive;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    url: '/relations/permissions';
};

export type UpdateRelationPermissionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRelationPermissionsError = UpdateRelationPermissionsErrors[keyof UpdateRelationPermissionsErrors];

export type UpdateRelationPermissionsResponses = {
    /**
     * Successful Response
     */
    200: Relation;
};

export type UpdateRelationPermissionsResponse = UpdateRelationPermissionsResponses[keyof UpdateRelationPermissionsResponses];

export type UpdateViewPermissionsData = {
    body: Permissive;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    url: '/views/permissions';
};

export type UpdateViewPermissionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateViewPermissionsError = UpdateViewPermissionsErrors[keyof UpdateViewPermissionsErrors];

export type UpdateViewPermissionsResponses = {
    /**
     * Successful Response
     */
    200: OsintView;
};

export type UpdateViewPermissionsResponse = UpdateViewPermissionsResponses[keyof UpdateViewPermissionsResponses];

export type DeleteEntityData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    url: '/entities';
};

export type DeleteEntityErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEntityError = DeleteEntityErrors[keyof DeleteEntityErrors];

export type DeleteEntityResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
